### ISSUE TITLE
Apply language changes immediately

### ISSUE THREAD

**Issue by DraSa** [Elytherion/tdeheroes#24]
TDE5 Heroes Client v0.47.1
While switching the interface language, the changes apply only after you reopen the file.
I think it would be better to switch the language right after the user resets it. Or at least inform the user that the file has to be reopened.

**Comment by Elytherion** [comment]
I first tried to make language changes happen immediately, but it isnt safe to change all the entry names. If you open a character created in German and now you switch to English, many entries will not be available, because the corresponding English books are not yet available. So it would cause an error.
I know, currently it would be the same problem, but as a user you could see the problem as you load the char - and not right before finishing creation with not being able to save because of the error.
But you're right, I will add a hint in the settings window!
Thanks
Ely

**Comment by DraSa** [comment]
So the English locale is bound to the books that are currently available. Is it just because the terms are not translated yet, or because each locale has to function separately?
I am concerned because I was going to ask you whether you can add one more language. =)

**Comment by Elytherion** [comment]
It is just because the terms are not translated yet. The locale is entirely separated from the actual rules. I can add one more language, but I wont be able to provide the translations on my own as German and English are the only languages I can speak ;) I case you would translate entries and UI I could integrate it into the app!

**Comment by DraSa** [comment]
Well, actually there are some official publications in French and Russian as well. http://www.drivethrurpg.com/browse/pub/3444/Ulisses-Spiele?filters=0_0_0_0_45571 
In case you change your mind, I'd be glad to provide the Russian translations.

**Comment by Elytherion** [comment]
I added the hint in Settings modal to yesterday's update, as more translations won't be in 1.0.0 as stated in #66.
