### ISSUE TITLE
Are you planning to go open source with your CG?

### ISSUE THREAD

**Issue by theShmoo** [Elytherion/tdeheroes#25]

**Comment by Turakar** [comment]
I would also be interested in writing a web server which allows an easy management for primarily fights, but maybe also other features later on. It would be great, if I can for example use your storage format.

**Comment by theShmoo** [comment]
Hello Turakar,
Maybe you are interested in this tool I wrote:
https://github.com/theShmoo/DSA5CombatProtocol
It enables combat management for the game master for TBE.
Currently, it is only available in German.

**Comment by Elytherion** [comment]
Sadly, opensourcing is not possible. I wasn't sure about the legal restrictions and I got the answer, that I can not use their trademark for open source. So you can only view my code via the Chrome debugger, which can provide my compiled JS files. Because I now switched from webpack to plain tsc, you can also view the original file structure (my compiled src tree) starting with the next update.

**Comment by Elytherion** [comment]
In case someone is interested I can add you to my code repo. There are just a few restrictions for using the stuff (it is still under the Scriptorium license), but I have written them down there.

**Comment by BenSower** [comment]
Would love to have access to the repo (even if it's read-only)!

**Comment by Elytherion** [comment]
@BenSower I added you as a contributor! If you want to help coding, please contribute either by forking and using a **private** repo or by creating issues and new branches. Its just that I am working on a few things at once - as I am the only person working on the code right now and I got to some problems, so I am switching between them, once I found a way to go on with one of them - so some things might not work, which is intended.

**Comment by BenSower** [comment]
Thanks @Elytherion, I'll have a look at it :-)
