### ISSUE TITLE
Why not open source?

### ISSUE THREAD

**Issue by BenSower** [Elytherion/tdeheroes#58]
Since I come from a software-development background I was wondering if you couldn't make your code open source. From my personal experience I know that there are a lot of players (including myself) who also have a background in coding and could help you improve and push the project faster. There will be so many small edge cases and features that it won't be fun maintaing the code alone... 

Also, if there is some conservative "but then everyone could steal our IP!"-jumbo-mambo, you can tell them that all the rules are online here http://www.ulisses-regelwiki.de/index.php anyways. Making the code open source won't change that it's hard to generate a character without the actual detailed knowledge from the books. People won't buy the books because the rules are hidden so well that you have to buy the book to see them, but because the rules themselves are good.

so long, make TDE great again!

P.S.: Disassembling an electron app and therefore getting the code and the rulse isn't that hard either...

**Comment by Elytherion** [comment]
The problem with open source is Ulisses provides a license for the Scriptorium only. If I would have a public repo, it wouldnt fit their license. I asked them because of this.

Actually, I'm not working on my own. Heaps of work is needed to get all the crunch from the books into tables. I've got players helping me with entries needed for calculating stuff and players helping with texts from the books (e.g. spell effects). In terms of coding I still need to figure out how to design/implement all the different features needed (#10, #38, #39, #40, #41, #42, #43, #44).

**Comment by BenSower** [comment]
Hey Elytherion,

thanks for the answer! Yeah, I was expecting as much from Ulisses... Still, it would be less work for you, if more people had access to your code and could create pull-requests :-).

Take care!
